### ISSUE TITLE
hasStyle does not work for CSS variables

### ISSUE THREAD

**Issue by DingoEatingFuzz** [mainmatter/qunit-dom#1272]
## The bug

Consider this element:

```html
<div style="--my-var:123" />
```

The following assertion does not work:

```js
assert.dom('div').hasStyle({ '--my-var': 123 });
```

Since `hasStyle` is implemented with `getComputedStyle` and `getComputedStyle` returns styles after computations are resolved, variable styles are not present on the `CSSDeclaration` object.

In order to get the variable styles from an element you must use `element.style.getPropertyValue('--my-var')`.

## Motivation to have this behavior

An emerging pattern now that CSS variables have broad adoption is to dynamically set variables in JS/HTML and then read the variables in static CSS.

For instance:

```css
div {
  --my-var: 100; /* default value */
  height: var(--my-var); /* overridable from JS without hardcoding height */
  max-height: var(--my-var); /* implementation detail not the concern of JS */
}
```

## Proposed solution

I think the API for `hasStyle` can remain unchanged. The keys for the `expected` object can be divided into variables (start with `--`) and declarations. Then the two sets can be iterated over using `style.getPropertyValue` and `getComputedStyle` respectively.
